virb30/lml-commerce

- src/Domain/Entity/Product.ts
- src/Domain/ValueObjects/Email.ts
- test/Email.test.ts
- test/Example.test.ts
- test/Product.test.ts
> feat: add email value object

- src/Application/PlaceOrderUseCase.ts
- src/Domain/Entity/Order.ts
- src/Domain/Entity/OrderItem.ts
- src/Domain/Repository/ProductRepository.ts
- src/Infra/Repository/ProductRepositoryMemory.ts
- test/Order.test.ts
- test/OrderItem.test.ts
- test/PlaceOrderUseCase.test.ts
Co-authored-by: Vinícius Bôscoa <virb30@gmail.com>
Co-authored-by: Sebastião Félix <sebastiaofelix@users.noreply.github.com>
Co-authored-by: Marciofernandes12 <marciofernandes2@outlook.com>
> Co-authored-by: lucasaecio <lucasaecio@users.noreply.github.com>

- src/Domain/Entity/Product.ts
- test/Product.test.ts
Makes dimensions and weight params optional; 
Adds validation rules to weight property;
Adds getVolume method to Product entity to prevent logic leak to other components
closes: #13
> improve Product entity

- .editorconfig
- .eslintrc.json
- .husky/pre-commit
- .lintstagedrc.json
- .prettierrc
- jest.config.ts
- package-lock.json
- package.json
- src/Application/PlaceOrderUseCase.ts
- src/Domain/Entity/Order.ts
- src/Domain/Entity/OrderItem.ts
- src/Domain/Entity/Product.ts
- src/Domain/Repository/OrderRepository.ts
- src/Domain/Repository/ProductRepository.ts
- src/Domain/ValueObjects/Dimensions.ts
- src/Domain/ValueObjects/Email.ts
- src/Domain/ValueObjects/Id.ts
- src/Infra/Database/Connection.ts
- src/Infra/Database/MysqlConnectionAdapter.ts
- src/Infra/Repository/OrderRepositoryMemory.ts
- src/Infra/Repository/ProductRepositoryMemory.ts
- src/config.ts
- test/Dimensions.test.ts
- test/Email.test.ts
- test/Id.test.ts
- test/MysqlConnectionAdapter.test.ts
- test/Order.test.ts
- test/OrderItem.test.ts
- test/PlaceOrderUseCase.test.ts
- test/Product.test.ts
> add styleguide and pre-commit hooks

- .commitlintrc.json
- .husky/commit-msg
- package-lock.json
- package.json
* Installs commitlint/cli package
* Installs commitlint/config-conventional package and configures commitlint to use it
* Configure husky to prevent wrong commit messages
closes #34
> chore: add commit lint

- src/Domain/Entity/Coupon.ts
- test/Coupon.test.ts
> feat(Coupon): [#20] Create Coupon

- package-lock.json
- package.json
- src/Infra/Http/ExpressHttpAdapter.ts
- src/Infra/Http/Http.ts
- src/main.ts
- test/ExpressHttpAdapter.test.ts
Adds Http server and ExpressHttpAdapter
closes #23
> feat(api): [#23] implements http server

- src/Domain/Repository/ProductRepository.ts
- src/Domain/ValueObjects/Dimensions.ts
- src/Infra/Repository/ProductRepositoryDatabase.ts
- src/Infra/Repository/ProductRepositoryMemory.ts
- test/ProductRepositoryDatabase.test.ts
> feat(Product): [#41] Create Repository

- src/Domain/Entity/Order.ts
- src/Domain/Entity/OrderItem.ts
- test/Order.test.ts
- test/OrderItem.test.ts
> feat: validate duplication of order items

- .github/workflows/build.yml
- migrations/database.sql
* add drop table to database.sql
* improve workflow
closes: #33
> chore: [#33] add drop table commands to migrations

- package-lock.json
- package.json
- src/Infra/Controller/Controller.ts
- src/Infra/Controller/OrderController.ts
- src/Infra/Http/ExpressHttpAdapter.ts
- src/Infra/Http/Http.ts
- src/Infra/Repository/ProductRepositoryMemory.ts
- test/ExpressHttpAdapter.test.ts
- test/OrderController.test.ts
* adds OrderController with POST method to Place an order
* Implements abstract class Controller as a helper to build outputs for controllers
* adjusts typings of Http interface and its dependencies
closes #48
> implements OrderController

- migrations/database.sql
- src/Domain/Entity/Coupon.ts
- src/Domain/Repository/CouponRepository.ts
- src/Infra/Repository/CouponRepositoryDatabase.ts
- test/CouponRepositoryDatabase.test.ts
> feat(Order): [#44] Create CouponRepository

- migrations/database.sql
- src/Application/PlaceOrderUseCase.ts
- src/Domain/Entity/Coupon.ts
- src/Domain/Entity/Order.ts
- src/Domain/Entity/OrderCoupon.ts
- src/Infra/Controller/OrderController.ts
- src/Infra/Repository/CouponRepositoryMemory.ts
- src/Infra/Repository/OrderRepositoryDatabase.ts
- test/Coupon.test.ts
- test/Order.test.ts
- test/OrderController.test.ts
- test/OrderCoupon.test.ts
- test/OrderRepositoryDatabase.test.ts
- test/PlaceOrderUseCase.test.ts
> feat(Coupon): [#11] implements logic coupon apply

- src/Infra/Repository/OrderRepositoryDatabase.ts
- src/Infra/Repository/ProductRepositoryDatabase.ts
- test/OrderRepositoryDatabase.test.ts
- test/ProductRepositoryDatabase.test.ts
* ProducRepositoryDatabase: Throw an error if Product not found
* OrderRepositoryDatabase: Throw an error if Order not found
closes #58
> Fix: throw errors in repositories

- migrations/database.sql
- src/Application/GetStockUseCase.ts
- src/Domain/Entity/StockEntry.ts
- src/Domain/Repository/StockEntryRepository.ts
- src/Domain/Service/StockCalculator.ts
- src/Infra/Repository/StockEntryRepositoryDatabase.ts
- src/Infra/Repository/StockEntryRepositoryMemory.ts
- test/GetStockUseCase.test.ts
- test/StockCalculator.test.ts
- test/StockEntry.test.ts
- test/StockEntryRepositoryDatabase.test.ts
* Adds StockEntry Entity
* Adds StockCalculator Domain Service
* Adds GetStockUseCase
* Adds StockEntry repositories (database and memory)
* Adds migration to create stock_entry table
closes #21
> Implements Domain Stock

- src/Application/GetStockUseCase.ts
- src/Application/PlaceOrderUseCase.ts
- src/Application/SimulateFreightUseCase.ts
- src/Domain/Factory/RepositoryFactory.ts
- src/Infra/Controller/OrderController.ts
- src/Infra/Factory/DatabaseRepositoryFactory.ts
- src/Infra/Factory/MemoryRepositoryFactory.ts
- src/main.ts
- test/GetStockUseCase.test.ts
- test/OrderController.test.ts
- test/PlaceOrderUseCase.test.ts
- test/SimulateFreightUseCase.test.ts
* Adds Abstract Factory with Singleton patterns to repositories
closes #51
> #51 Adds Repository factory

- src/Application/ValidateCouponUseCase.ts
- test/ValidateCouponUseCase.test.ts
> feat(Coupon): [#40] Create validate coupon usecase

- src/Application/Checkout/PlaceOrderUseCase.test.ts
- src/Application/Checkout/PlaceOrderUseCase.ts
- src/Application/Stock/handler/StockHandler.test.ts
- src/Application/Stock/handler/StockHandler.ts
- src/Domain/@shared/Event/DomainEvent.ts
- src/Domain/Checkout/Event/OrderPlaced.test.ts
- src/Domain/Checkout/Event/OrderPlaced.ts
- src/Infra/@shared/Queue/MemoryQueueAdapter.test.ts
- src/Infra/@shared/Queue/MemoryQueueAdapter.ts
- src/Infra/@shared/Queue/Queue.ts
- src/Infra/Checkout/Controller/OrderController.test.ts
- src/Infra/Checkout/Controller/OrderController.ts
- src/Infra/Stock/Controller/StockController.test.ts
- src/Infra/Stock/Controller/StockController.ts
- src/main.ts
> feat(event): implements order placed event with queue

- .eslintignore
- .eslintrc.json
- .prettierrc
- package-lock.json
- package.json
- src/Infra/@shared/Controller/HealthCheckController.ts
- src/Infra/@shared/DI/Registry.test.ts
- src/Infra/@shared/DI/Registry.ts
- src/Infra/@shared/Database/MysqlConnectionAdapter.test.ts
- src/Infra/@shared/Database/MysqlConnectionAdapter.ts
- src/Infra/@shared/Http/Http.ts
- src/Infra/Checkout/Controller/OrderController.test.ts
- src/Infra/Checkout/Controller/OrderController.ts
- src/Infra/Checkout/Repository/Database/CouponRepositoryDatabase.ts
- src/main.ts
- tsconfig.json
Implementation of a Dependency Injection Container using Singleton, Registry, Decorator and Proxy patterns combined.
closes #84
> Implements Dependency Injection container

- src/Application/Catalog/GetProductsQuery.test.ts
- src/Application/Catalog/GetProductsQuery.ts
> feat(getProducts): [ISSUE-38] implements GetProductsQuery

- migrations/database.sql
- src/Modules/ProductAdmin/Domain/Entity/Product.test.ts
- src/Modules/ProductAdmin/Domain/Entity/Product.ts
- src/Modules/ProductAdmin/Domain/Event/ProductCreated.test.ts
- src/Modules/ProductAdmin/Domain/Event/ProductCreated.ts
- src/Modules/ProductAdmin/Domain/Repository/ProductRepository.ts
- src/Modules/ProductAdmin/Repository/Database/ProductRepositoryDatabase.test.ts
- src/Modules/ProductAdmin/Repository/Database/ProductRepositoryDatabase.ts
- src/Modules/ProductAdmin/Repository/Memory/ProductRepositoryMemory.ts
- src/Modules/ProductAdmin/UseCase/CreateProductUseCase.test.ts
- src/Modules/ProductAdmin/UseCase/CreateProductUseCase.ts
> Implements CreateProductUseCase

- src/modules/stock/domain/entity/product.entity.spec.ts
- src/modules/stock/domain/entity/product.entity.ts
- src/modules/stock/domain/entity/stock-entry.entity.spec.ts
- src/modules/stock/domain/entity/stock-entry.entity.ts
- src/modules/stock/domain/event/stock-product-added.event.ts
- src/modules/stock/domain/repository/product.repository.interface.ts
- src/modules/stock/queue/stock.processor.ts
- src/modules/stock/repository/memory/product.repository.ts
- src/modules/stock/usecase/add-product-stock.usecase.spec.ts
- src/modules/stock/usecase/add-product-stock.usecase.ts
> feat(stock): [#73] add product stock use case

- jest.config.ts
- src/modules/product-adm/domain/entity/product.spec.ts
- src/modules/product-adm/domain/entity/product.ts
- src/modules/product-adm/domain/event/product-updated.event.spec.ts
- src/modules/product-adm/domain/event/product-updated.evet.ts
- src/modules/product-adm/repository/database/product.repository.ts
- src/modules/product-adm/repository/memory/product.repository.ts
- src/modules/product-adm/usecase/update-product.usecase.spec.ts
- src/modules/product-adm/usecase/update-product.usecase.ts
- src/modules/shared/domain/value-object/currency.spec.ts
- src/modules/shared/domain/value-object/currency.ts
> feat(Product): [#72] Create update use case for product

- backend/src/modules/product-adm/domain/entity/product.spec.ts
- backend/src/modules/product-adm/domain/entity/product.ts
- backend/src/modules/product-adm/repository/database/product.repository.spec.ts
- backend/src/modules/product-adm/repository/database/product.repository.ts
- backend/src/modules/product-adm/usecase/create-product.usecase.spec.ts
- backend/src/modules/product-adm/usecase/create-product.usecase.ts
- backend/src/modules/product-adm/usecase/update-product.usecase.spec.ts
- backend/src/modules/product-adm/usecase/update-product.usecase.ts
fix: differences between product format price of product-adm and checkout modules
closes: #99
> [#99] Fix divergences in prices

- .gitignore
- backend/README.md
- docker-compose.yaml
Add keycloak and db-keycloak services to docker-compose.yaml file
> Add keycloak with db containers to compose file
